pipeline {
    agent any
    stages {
        stage('Build') {
            steps { sh 'make' }
        }
        stage('Test') {
            parallel {
                stage('Unit') { steps { sh 'make unit' } }
                stage('Lint') { steps { sh 'make lint' } }
            }
        }
        stage('Deploy') {
            steps { sh 'make deploy' }
        }
    }
}
